first commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,8 +34,8 @@ jobs:
 
       - name: Test SonarQube connectivity
         run: |
-          curl -v -f http://sonarqube.192.168.2.189.nip.io || echo "Failed to reach SonarQube via Ingress"
-          curl -v -f http://192.168.2.189:30000 || echo "Failed to reach SonarQube via NodePort"
+          curl -v -f http://sonarqube.192.168.2.81.nip.io || echo "Failed to reach SonarQube via Ingress"
+          curl -v -f http://192.168.2.81:30000 || echo "Failed to reach SonarQube via NodePort"
 
       - name: Run tests with JaCoCo
         run: mvn test jacoco:report
@@ -47,7 +47,7 @@ jobs:
           for i in {1..3}; do
             mvn sonar:sonar -X \
               -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
-              -Dsonar.host.url=http://sonarqube.192.168.2.189.nip.io \
+              -Dsonar.host.url=http://sonarqube.192.168.2.81.nip.io \
               -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
               -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml && break
             echo "Attempt $i failed, retrying in 10 seconds..."
@@ -74,7 +74,7 @@ jobs:
       - name: Checkout k8s-manifests repository
         uses: actions/checkout@v4
         with:
-          repository: SeifeddineABIDI/k8s-manifests
+          repository: AchouriMarwen/k8s-manifests
           path: manifests
           token: ${{ secrets.GH_PAT }}
 
@@ -82,8 +82,8 @@ jobs:
         run: |
           sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/approbation-backend:${{ github.sha }}|" manifests/backend/deployment.yaml
           cd manifests
-          git config user.name "seifeddineAbidi"
-          git config user.email "seifeddine.abidi@esprit.tn"
+          git config user.name "AchouriMarwen"
+          git config user.email "marwen.achouri@esprit.tn"
           git add .
           if git diff --staged --quiet; then
             echo "No changes to commit"
