Test CI with sonar stage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,27 +32,27 @@ jobs:
       - name: Build with Maven
         run: mvn clean package -DskipTests
 
-     # - name: Test SonarQube connectivity
-      #  run: |
-       #   curl -v -f http://sonarqube.192.168.2.81.nip.io || echo "Failed to reach SonarQube via Ingress"
-        #  curl -v -f http://192.168.2.81:30000 || echo "Failed to reach SonarQube via NodePort"
+      - name: Test SonarQube connectivity
+        run: |
+          curl -v -f http://sonarqube.192.168.2.81.nip.io || echo "Failed to reach SonarQube via Ingress"
+          curl -v -f http://192.168.2.81:30000 || echo "Failed to reach SonarQube via NodePort"
 
-     # - name: Run tests with JaCoCo
-      #  run: mvn test jacoco:report
+      - name: Run tests with JaCoCo
+        run: mvn test jacoco:report
 
-     # - name: Run SonarQube analysis
-      #  env:
-       #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        #run: |
-         # for i in {1..3}; do
-          #  mvn sonar:sonar -X \
-           #   -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
-            #  -Dsonar.host.url=http://sonarqube.192.168.2.81.nip.io \
-             # -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
-              #-Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml && break
-            #echo "Attempt $i failed, retrying in 10 seconds..."
-            #sleep 10
-          ##done
+      - name: Run SonarQube analysis
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          for i in {1..3}; do
+            mvn sonar:sonar -X \
+              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
+              -Dsonar.host.url=http://sonarqube.192.168.2.81.nip.io \
+              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
+              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml && break
+            echo "Attempt $i failed, retrying in 10 seconds..."
+            sleep 10
+          done
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
